name: atlantis-terragrunt

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "TODAY=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
    - name: build :${{env.TODAY}} image
      run: |
        docker build -t ghcr.io/rungway/atlantis-terragrunt:${{env.TODAY}} .
    - name: publish atlantis-terragrunt:${{env.TODAY}} image
      run: |
        docker push ghcr.io/rungway/atlantis-terragrunt:${{env.TODAY}}
        docker tag ghcr.io/rungway/atlantis-terragrunt:${{env.TODAY}} ghcr.io/rungway/atlantis-terragrunt:latest
        docker push ghcr.io/rungway/atlantis-terragrunt:latest
    # - name: Login to Docker Hub registry
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USER }}
    #     password: ${{ secrets.DOCKER_HUB_KEY }}
    # - name: publish atlantis-terragrunt:${{env.TODAY}} image to Docker Hub
    #   run: |
    #     docker tag ghcr.io/rungway/atlantis-terragrunt:${{env.TODAY}} rungway/atlantis-terragrunt:latest
    #     docker tag ghcr.io/rungway/atlantis-terragrunt:${{env.TODAY}} rungway/atlantis-terragrunt:${{env.TODAY}}
    #     docker push rungway/atlantis-terragrunt:${{env.TODAY}}
    #     docker push rungway/atlantis-terragrunt:latest
